doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
        driver: 'mysql'
        server_version: '5.7'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
          changelog: CsrDelft\common\ChangeLogType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            CsrDelft:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/lib/entity'
                prefix: 'CsrDelft\entity'
                alias: App
        second_level_cache:
          region_cache_driver:
            type: service
            id: memcached_cache_service
          enabled: true
          region_lifetime: 86400

services:
    memcached_service:
      class: Memcached
      calls:
        - [addServer, ["%env(CACHE_PATH)%csrdelft-cache.socket", 0]]

    memcached_cache_service:
      class: Doctrine\Common\Cache\MemcachedCache
      calls:
        - [setMemcached, ["@memcached_service"]]
