language: php
php:
  - 7

cache:
  directories:
    - "node_modules"
    - "vendor"

git:
  submodules: false

before_install:
  - cp ./lib/defines.include.php.sample ./lib/defines.include.php
  - nvm install 8

install:
  - yarn
  - composer install

script:
  - yarn run production
  - composer run-script production

deploy:
  provider: script
  script: ./bin/ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
