language: php
php:
  - 7

git:
  depth: false

cache:
  directories:
    - "node_modules"
    - "vendor"

env:
  global:
    - SKIP_BUILD=`[[ $TRAVIS_COMMIT_MESSAGE == *"[skipbuild]"* ]]; echo $?`

jobs:
  include:
    - stage: build
      services: mysql
      before_install: nvm install 8
      script: ./bin/ci/build.sh
      deploy:
        provider: script
        script: ./bin/ci/deploy.sh
        skip_cleanup: true
        on:
          branch: master
      if: type != pull_request
    - stage: analysis
      script: sonar-scanner
      if: branch = master OR type = pull_request
      addons:
        sonarcloud:
          organization: "csrdelft"

stages:
  - build
  - analysis

script: skip
