language: php
php:
  - 7

cache:
  directories:
    - "node_modules"
    - "vendor"

addons:
  sonarcloud:
    organization: "csrdelft"

services:
  - mysql

before_install:
  - cp ./bin/ci/mysql.ini.travis ./etc/mysql.ini
  - cp ./bin/ci/defines.include.php ./lib/defines.include.php
  - mysql -e 'CREATE DATABASE IF NOT EXISTS csrdelft;'
  - nvm install 8

install:
  - yarn
  - composer install

script: # Let op met gebruik van deze opties, als er iets niet gebuild wordt wat wel had moeten gebeuren is het je eigen schuld.
  - if [[ $TRAVIS_COMMIT_MESSAGE != *"[skipjs]"* ]]; then yarn run production; fi;
  - if [[ $TRAVIS_COMMIT_MESSAGE != *"[skipphp]"* ]]; then composer run-script production; fi;
  - if [[ $TRAVIS_COMMIT_MESSAGE != *"[skipsonar]"* ]]; then sonar-scanner; fi;

deploy:
  provider: script
  script: ./bin/ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
