language: node_js

cache:
  directories:
    - "node_modules"

install: npm install

script:
  - npm run production

deploy:
  provider: script
  script: ./bin/ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master