stek:
  build: .
  links:
    - stekdb:db
  ports:
    - "8080:80"
  volumes:
    - htdocs/plaetjes:/var/www/csrdelft.nl/htdocs/plaetjes

stekdb:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: bl44t
    MYSQL_USER: csrdelft
    MYSQL_PASSWORD: bl44t
    MYSQL_DATABASE: csrdelft
  volumes:
    - db/:/var/lib/mysql/
