upload:
  path: /plaatjes/upload
  controller: CsrDelft\controller\PlaatjesController::upload
  methods: [GET,POST]
  defaults: { _mag: P_LOGGED_IN }
bekijken:
  path: /plaatjes/bekijken/{id}
  controller: CsrDelft\controller\PlaatjesController::bekijken
  methods: GET
  requirements: { id: '[a-zA-Z0-9]*' }
  defaults: { _mag: P_LOGGED_IN }
